// Generated by CoffeeScript 1.9.0
var app;

app = angular.module('App', []);

app.controller('Calendar', [
  '$scope', function($scope) {
    var locale, month, now, year;
    locale = 'en-us';
    now = new Date();
    year = now.getFullYear();
    month = now.getMonth();
    $scope.monthNum = month;
    $scope.yearNum = year;
    $scope.month = function() {
      var date;
      date = new Date($scope.yearNum, $scope.monthNum, 1);
      return date.toLocaleDateString(locale, {
        month: 'long'
      });
    };
    $scope.date = function(year, month) {
      return new Date(year, month, 1);
    };
    $scope.$watch('month', $scope.date);
  }
]).directive('monthView', function() {
  return {
    scope: {
      yearNum: '=',
      monthNum: '='
    },
    link: function(scope, element, attrs) {
      var setupMonth;
      scope.$watch('monthNum', function() {
        return setupMonth(new Date(scope.yearNum, scope.monthNum, 1));
      });
      window.xx = scope;
      console.log(scope);
      console.log(scope.yearNum, scope.monthNum);
      setupMonth = function(displayMonth) {
        var elm, firstDay, index, month, numDays, year, _i, _len, _ref, _results;
        year = displayMonth.getFullYear();
        month = displayMonth.getMonth();
        firstDay = displayMonth.getDay();
        numDays = (new Date(year, month + 1, 0)).getDate();
        _ref = document.querySelectorAll('.day');
        _results = [];
        for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
          elm = _ref[index];
          if (index < firstDay || index > numDays + firstDay - 1) {
            _results.push(elm.innerHTML = '');
          } else {
            _results.push(elm.innerHTML = index - firstDay + 1);
          }
        }
        return _results;
      };
      return setupMonth(new Date(scope.$parent.yearNum, scope.$parent.monthNum, 1));
    }
  };
});
