// Generated by CoffeeScript 1.9.1

/*
 * Helper Functions
 */
var END_TIME, START_TIME, app, dataService, mainController;

START_TIME = -2;

END_TIME = 24 + 3;


/*
 * START OF THE APP
 */

app = angular.module('App', ['ngRoute', 'calendarControllers', 'dayviewControllers']);


/*
 * MainController
 */

mainController = function($scope, $routeParams, $location) {
  $scope.showCalendar = function() {
    $location.url('/calendar');
    console.log('cal');
  };
  $scope.showDay = function(date) {
    $location.url("/day/" + date[0] + "/" + (date[1] + 1) + "/" + date[2]);
    console.log('day', date);
  };
  console.log($routeParams);
  $scope.abc = $routeParams.id || "default";
};

app.controller('MainController', ['$scope', '$routeParams', '$location', mainController]);

dataService = function($http, $q) {
  var data, deferred, failure, ret, success;
  deferred = $q.defer();
  success = function(response) {
    return deferred.resolve(response);
  };
  failure = function(response) {
    return deferred.reject(response);
  };
  $http.get("js/test-hangout-data.json").success(success).error(failure);
  data = deferred.promise;
  ret = {
    get: function(year, month, day) {
      var d, date;
      if (year instanceof Date) {
        day = year.getDate();
        month = year.getMonth() + 1;
        year = year.getFullYear();
      }
      date = new Date(year, month - 1, day);
      d = $q.defer();
      data.then(function(response) {
        console.log('resolving promise', response, date.toDateString());
        return d.resolve(response[date.toDateString()] || {});
      });
      return d.promise;
    }
  };
  return ret;
};

app.factory('dataService', ['$http', '$q', dataService]);

app.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/calendar', {
      templateUrl: 'calendar-template.html',
      controller: 'Calendar'
    }).when('/day', {
      templateUrl: 'dayview-template.html',
      controller: 'TimeViewController'
    }).when('/day/:year/:month/:day', {
      templateUrl: 'dayview-template.html',
      controller: 'TimeViewController'
    }).otherwise({
      redirectTo: '/calendar'
    });
  }
]);
